#' Constructor for \code{uniCont} objects
#' 
#' \code{uniCont} objects hold final test set univariate continuous predictions performed by models.
#' 
#' \code{uniCont} objects hold univariate continuous predictions performed by a model over a number
#' of test sets generated according to some resampling of the data. A tag exist
#' to connect the predictions with the object that contains information about
#' the selected test sets. This allows results from different models to be 
#' compared since two \code{uniCont} objects with the same tag are guaranteed 
#' to be generated from the same test set points.
#' 
#' @param resample_indexes S3 object of class \code{datasetResample} with information
#'  about the data used using for training and predictions. Usually
#'  generated by the \code{generateTestIndexes} function.
#' @param pred List where each element contains a numeric vector with predictions for 
#'  a given test set. 
#' @param summary_validation Object of class \code{summaryValidation}, usually
#'  created by \code{SummaryValidationMetric} function. Default to NULL, when
#'  no validation step is necessary.
#' @param metric_name Character vector indicating the name of the metric used
#'  in the validation step. Default to NULL, when no validation step 
#'  is necessary. See the help of \code{evaluateProbClass} function to
#'  which metrics are currently available.
#' @param weight_name Character element with the name of the variable used as weight in the
#'  model training
#' 
#' @return S3 object of class \code{uniCont}.
#' 
#' @family tgmUniCont constructors
#' @seealso \code{\link{generateTestIndexes}}, 
#'  \code{\link{summaryValidation}}, 
#'  \code{\link{evaluateProbClass}}
#' @export
uniCont <- function(resample_indexes, pred, 
                    summary_validation = NULL, 
                    metric_name = NULL, 
                    weight_name = NULL){
  
  object <- list(target_name = mcGet(resample_indexes, "target_name"), 
                 weight_name = weight_name,
                 pred = pred, 
                 datasetResample_tag = mcGet(resample_indexes, "tag"),
                 summary_validation = summary_validation,
                 metric_name = metric_name)
  class(object) <- c("uniCont")
  return(object)
  
}

#' Extract info from \code{uniCont} objects
#' 
#' @export
mcGet.uniCont <- function(x, attr, i = NULL){
  
  if (attr == "pred"){ # probability predictions
    
    if (is.null(i)){
      return(x[["pred"]])  
    } else {
      if (i >= 1 & i <= length(x[["pred"]])){
        result <- x[["pred"]][[i]]
        return(result)
      } else {
        stop("index i out of range.")
      }
    }
    
  } else if (attr == "number_replicates"){ # number of prediction sets
    
    return(length(x[["pred"]]))
    
  } else if (attr == "target_name"){ # class labels
    
    return(x[["target_name"]])
    
  } else if (attr == "weight_name"){ # weight variable name
    
    return(x[["weight_name"]])
    
  } else if (attr == "tag"){ # resample indexes tag
    
    return(x[["datasetResample_tag"]])
    
  } else if (attr == "summary_validation"){ # Validation Summary
    
    summary_validation <- x[["summary_validation"]]
    if (is.null(summary_validation)){
      return(NULL)
    } else if (is.null(i)){
      return(summary_validation)
    } else if (i == "parameter_names"){
      parameter_names <- colnames(summary_validation)
      parameter_names <- parameter_names[-c(1, length(parameter_names))]
      return(parameter_names)
    } else {
      stop("Invalid i option for summary_validation")
    }
    
  } else if (attr == "metric_name"){ # Metric name used to evaluate models
    
    return(x[["metric_name"]])
    
  } else {
    stop(attr, " not found.")
  }
  
}