#' Constructor for \code{uniContValidation} objects
#' 
#' \code{uniContValidation} objects hold validation set predictions performed by different models.
#' 
#' \code{uniContValidation} objects hold univariate continuous predictions performed 
#' by different models over the same validation set. A tag exist
#' to connect the predictions with the object that contains information about
#' the selected validation set. In addition the specific replicate index of the
#' validation set used is stored because several validation sets are contained in the
#' tagged object.
#' 
#' @param resample_indexes S3 object of class \code{datasetResample} with information
#'  about Class Labels and the data used using for training and predictions. Usually
#'  generated by the \code{generateTestIndexes} function.
#' @param pred List where each element contains a numeric vector with predictions performed 
#'  by a model on the same validation set. 
#' @param replicate_index Integer number that indicates which validation set was used.
#' @param tune_grid It is a matrix with named columns containing tuning parameters of the
#'  model. Each row of the matrix represents tuning parameter values of a specific model.
#' @param weight_name Character element with the name of the variable used as weight in the
#'  model training
#'  
#' @return S3 object of class \code{uniContValidation}.
#' 
#' @family tgmUniCont constructors
#' @seealso \code{\link{generateTestIndexes}}
#' @export 
uniContValidation <- function(resample_indexes, pred, replicate_index, tune_grid, 
                              weight_name = NULL){
  
  object <- list(target_name = mcGet(resample_indexes, "target_name"), 
                 weight_name = weight_name,
                 pred = pred, 
                 datasetResample_tag = mcGet(resample_indexes, "tag"),
                 replicate_index = replicate_index,
                 tune_grid = tune_grid)
  class(object) <- c("uniContValidation")
  return(object)
  
}

#' Extract info from \code{uniContValidation} objects
#' 
#' @export
mcGet.uniContValidation <- function(x, attr, i = NULL){
  
  if (attr == "pred"){ # predictions
    
    if (is.null(i)){
      return(x[["pred"]])  
    } else {
      if (i >= 1 & i <= length(x[["pred"]])){
        result <- x[["pred"]][[i]]
        return(result)
      } else {
        stop("index i out of range.")
      }
    }
    
  } else if (attr == "number_models"){ # number of models that made predictions
    
    return(length(x[["pred"]]))
    
  } else if (attr == "target_name"){ # class labels
    
    return(x[["target_name"]])
    
  } else if (attr == "weight_name"){ # weight name
    
    return(x[["weight_name"]])
    
  } else if (attr == "tag"){ # resample indexes tag
    
    return(x[["datasetResample_tag"]])
    
  } else if (attr == "replicate_index"){ # Which validation set was used
    
    return(x[["replicate_index"]])
    
  } else if (attr == "tune_grid"){ # Which validation set was used
    
    return(x[["tune_grid"]])
    
  } else {
    stop(attr, " not found.")
  }
  
}

#' Summarize results from the validation step
#' 
#' @export
summarizeValidation.uniCont <- function(fitted_model, ...){
 
  class(fitted_model) <- "multiClass"
  # For now both follow the same logic
  summarizeValidation(fitted_model, ...)
  
}  
